[package]
name = "logbook_3"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"
authors = ["John Arundel <john@bitfieldconsulting.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.89"
